name: Zuki [ Simran's personal assistant Bot]
permissions:
  issues: write
  contents: read
on:
  issues:
    types: [opened]

jobs:
  chatbot-response:
    runs-on: ubuntu-latest
    steps:
      - name: Respond to HR Question
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();

            let response = "Thanks for your question! I'll get back to you soon.";

            if (issueTitle.includes("notice period")) {
              response = "Hi! My notice period is 30 days 😊";
            } else if (issueTitle.includes("experience")) {
              response = "I have 5+ years of experience in DevOps, Kubernetes, and Cloud Automation.";
            } else if (issueTitle.includes("salary expectation")) {
              response = "My expected CTC is negotiable based on role and responsibility.";
            } else if (issueTitle.includes("location preference")) {
              response = "I'm open to remote and hybrid work opportunities.";
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: response
            });
